export const TODO_REQUEST = 'TODO_REQUEST'
export const TODO_SUCCESS = 'TODO_SUCCESS'
export const TODO_FALIURE = 'TODO_FALIURE'

export const TODO_POST_REQUEST = 'TODO_POST_REQUEST'
export const TODO_POST_SUCCESS = 'TODO_POST_SUCCESS'
export const TODO_POST_FALIURE = 'TODO_POST_FALIURE'
